# Generated by Django 2.1.7 on 2019-04-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('funds', models.IntegerField(default=0)),
            ],
        ),
    ]
