# Generated by Django 2.1.7 on 2019-04-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='club',
            name='club_name',
            field=models.CharField(max_length=100),
        ),
    ]
